---
name: "Clang format check"
"on":
  push:
    branches:
    - "master"
  pull_request:
    branches:
    - "master"
permissions:
  contents: "read"
jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
    - name: clang-format Check
      uses: jidicula/clang-format-action@v4.14.0
